repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.10
      hooks:
          - id: ruff
            args: [--fix]

    - repo: https://github.com/hhatto/autopep8
      rev: v2.3.2
      hooks:
          - id: autopep8

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.15.0
      hooks:
          - id: mypy
