repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          - --autofix
          - --indent
          - "\t"
      - id: requirements-txt-fixer
      - id: check-docstring-first
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language: system
        args: ["--fast"]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        language: system

  - repo: https://github.com/myint/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: ["--in-place", "--recursive", "--wrap-summaries", "79"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat

  - repo: https://github.com/djlint/djlint
    rev: v1.36.4
    hooks:
      - id: djlint
        args: ["--lint", "--reformat"]
        files: \.html$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        args: ["--config-file", "mypy.ini"]
        files: ^(svs_core|tests|docs)/
        language: system
