[project]
name = "svs_core"
version = "0.1.0"
description = "Core library for SVS"
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
packages = ["svs_core"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 88
target-version = "py313"
ignore = ["E712"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict = true
exclude = ["alembic", "conftest.py"]
#plugins = ["sqlalchemy.ext.mypy.plugin"]
