[project]
name = "svs_core"
version = "0.1.0"
description = "Core library for SVS"
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
packages = ["svs_core"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 88
target-version = "py311"
ignore = ["E712"]

[tool.ruff.isort]
known-first-party = ["svs_core"]
combine-as-imports = true
force-sort-within-sections = true
lines-between-types = 1
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
disallow_untyped_decorators = false
strict = true
exclude = ["^alembic/"]

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_decorators = false

[[tool.mypy.overrides]]
module = "svs_core.*"
disallow_untyped_decorators = true

[tool.isort]
profile = "black"
line_length = 88

[tool.black]
line-length = 88
target-version = ['py311']
