"""create basic user

Revision ID: f53d9df2b1bb
Revises:
Create Date: 2025-05-18 13:41:41.644013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f53d9df2b1bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('migratehistory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'migratehistory',
        sa.Column(
            'id',
            sa.INTEGER(),
            autoincrement=True,
            nullable=False),
        sa.Column(
            'name',
            sa.VARCHAR(
                length=255),
            autoincrement=False,
            nullable=False),
        sa.Column(
            'migrated_at',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False),
        sa.PrimaryKeyConstraint(
            'id',
            name='migratehistory_pkey'))
    op.drop_table('user')
    # ### end Alembic commands ###
