"""add mixins + ssh key contents

Revision ID: f8bb6dfb48bc
Revises: 3beb73b04313
Create Date: 2025-05-18 14:14:41.254785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8bb6dfb48bc'
down_revision: Union[str, None] = '3beb73b04313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ssh_key',
        sa.Column(
            'content',
            sa.String(
                length=4096),
            nullable=False))
    op.add_column(
        'ssh_key',
        sa.Column(
            'created_at',
            sa.DateTime(
                timezone=True),
            nullable=False))
    op.add_column(
        'ssh_key',
        sa.Column(
            'modified_at',
            sa.DateTime(
                timezone=True),
            nullable=False))
    op.drop_column('ssh_key', 'line_number')
    op.add_column(
        'user',
        sa.Column(
            'created_at',
            sa.DateTime(
                timezone=True),
            nullable=False))
    op.add_column(
        'user',
        sa.Column(
            'modified_at',
            sa.DateTime(
                timezone=True),
            nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'modified_at')
    op.drop_column('user', 'created_at')
    op.add_column(
        'ssh_key',
        sa.Column(
            'line_number',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False))
    op.drop_column('ssh_key', 'modified_at')
    op.drop_column('ssh_key', 'created_at')
    op.drop_column('ssh_key', 'content')
    # ### end Alembic commands ###
