# Generated by Django 6.0 on 2026-01-08 17:39

import django.db.models.deletion

from django.db import migrations, models

import svs_core.db.models


class Migration(migrations.Migration):

    replaces = [
        ("svs_core", "0001_initial"),
        ("svs_core", "0002_remove_servicemodel_status"),
        ("svs_core", "0003_rename_env_servicemodel__env_and_more"),
        (
            "svs_core",
            "0004_alter_servicemodel__env_alter_servicemodel__labels_and_more",
        ),
        ("svs_core", "0005_templatemodel__default_contents"),
        ("svs_core", "0006_gitsourcemodel"),
        ("svs_core", "0007_gitsourcemodel_downloaded_at"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "IMAGE"), ("build", "BUILD")],
                        default=svs_core.db.models.TemplateType["IMAGE"],
                        max_length=10,
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("dockerfile", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("_default_env", models.JSONField(blank=True, default=list, null=True)),
                (
                    "_default_ports",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "_default_volumes",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("start_cmd", models.CharField(blank=True, max_length=512, null=True)),
                ("_healthcheck", models.JSONField(blank=True, default=dict, null=True)),
                ("_labels", models.JSONField(blank=True, default=list, null=True)),
                ("args", models.JSONField(blank=True, default=list, null=True)),
                (
                    "_default_contents",
                    models.JSONField(blank=True, default=list, null=True),
                ),
            ],
            options={
                "db_table": "templates",
            },
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="ServiceModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "container_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("_env", models.JSONField(blank=True, default=list, null=True)),
                (
                    "_exposed_ports",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("_volumes", models.JSONField(blank=True, default=list, null=True)),
                ("command", models.CharField(blank=True, max_length=512, null=True)),
                ("_labels", models.JSONField(blank=True, default=list, null=True)),
                ("args", models.JSONField(blank=True, default=list, null=True)),
                ("_healthcheck", models.JSONField(blank=True, default=dict, null=True)),
                ("_networks", models.JSONField(blank=True, default=list, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="svs_core.templatemodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="svs_core.usermodel",
                    ),
                ),
            ],
            options={
                "db_table": "services",
            },
        ),
        migrations.CreateModel(
            name="GitSourceModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("repository_url", models.CharField(max_length=512)),
                ("branch", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "destination_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_sources",
                        to="svs_core.servicemodel",
                    ),
                ),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "git_sources",
            },
        ),
    ]
