# Generated by Django 6.0 on 2026-01-06 15:26

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svs_core", "0005_templatemodel__default_contents"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitSourceModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("repository_url", models.CharField(max_length=512)),
                ("branch", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "destination_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_sources",
                        to="svs_core.servicemodel",
                    ),
                ),
            ],
            options={
                "db_table": "git_sources",
            },
        ),
    ]
