# Generated by Django 6.0 on 2026-01-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svs_core", "0006_gitsourcemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitsourcemodel",
            name="downloaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
