# Generated by Django 6.0 on 2026-01-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svs_core", "0001_squashed_0007_gitsourcemodel_downloaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitsourcemodel",
            name="is_temporary",
            field=models.BooleanField(default=False),
        ),
    ]
