# Generated by Django 6.0 on 2026-01-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("svs_core", "0008_gitsourcemodel_is_temporary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gitsourcemodel",
            name="downloaded_at",
        ),
    ]
