services:
    db:
        image: postgres:latest
        restart: unless-stopped
        env_file:
            - .env.ci
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            #- ./pg-init:/docker-entrypoint-initdb.d:ro

    caddy:
        image: lucaslorentz/caddy-docker-proxy:latest
        container_name: caddy
        restart: unless-stopped
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - caddy_data:/data
        - caddy_config:/config
        environment:
        - CADDY_INGRESS_NETWORK=caddy
        networks:
        - caddy
        env_file:
            - .env.ci

volumes:
    pgdata:
    caddy_data:
    caddy_config:

networks:
    caddy:
        driver: bridge
