services:
    db:
        image: postgres:latest
        restart: unless-stopped
        env_file:
            - .env.ci
        ports:
            - "5432:5432"
        volumes:
            - ./pg-init:/docker-entrypoint-initdb.d:ro

    caddy:
        image: lucaslorentz/caddy-docker-proxy:latest
        container_name: caddy
        restart: unless-stopped
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - CADDY_INGRESS_NETWORK=caddy
        networks:
        - caddy
        env_file:
            - .env.ci

networks:
    caddy:
        driver: bridge
