import os
import re

from pathlib import Path

TEMPLATE_FILE = "docs/cli.md.template"
OUTPUT_DIRECTORY = "docs/cli-documentation"
OUTPUT_FILE = f"{OUTPUT_DIRECTORY}/index.md"

os.environ["DATABASE_URL"] = "sqlite:///./svs_core.db"


def generate_docs(file: str) -> str:
    """Generates CLI documentation using typer's built-in docs utility."""
    stream = os.popen(f"typer {file} utils docs --name svs")
    output = stream.read()
    exit_code = stream.close()

    if exit_code is not None:
        print(f"Error: Failed to generate docs for {file}.")
        exit(1)

    output = output.replace("SVS CLI\n\n", "")
    output = re.sub(
        r".*\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}: \[[A-Z]+\].*\n?", "", output
    )
    return output


def upgrade_headings(docs: str) -> str:
    """Upgrades headings by one level (e.g., ### becomes ##)."""
    return "\n".join(
        line[1:] if line.startswith("#") else line for line in docs.splitlines()
    )


def downgrade_headings(docs: str) -> str:
    """Downgrades headings by one level and comments out top-level headings."""
    return "\n".join(
        f"#{line}" if line.startswith("#") else line for line in docs.splitlines()
    )


def extract_root_command_info(docs: str) -> str:
    """Extracts just the root command info (before first group)."""
    # Find everything up to the first ### heading
    match = re.match(r"(.*?)(?=\n### `svs |$)", docs, re.DOTALL)
    return match.group(1).strip() if match else docs


def extract_group_documentation(docs: str, group_name: str) -> str:
    """Extracts documentation for a specific command group."""
    # Find the group section and all its subcommands
    pattern = rf"### `svs {group_name}`\n\n.*?(?=\n### `svs |\Z)"
    match = re.search(pattern, docs, re.DOTALL)
    if match:
        return match.group(0).strip()
    return ""


def split_into_groups(docs: str) -> tuple[str, dict[str, str]]:
    """Splits documentation into command groups."""
    # Extract the root documentation (before first ### heading)
    root_match = re.match(r"(.*?)(?=\n### `svs )", docs, re.DOTALL)
    root_docs = root_match.group(1).strip() if root_match else ""

    # Find all group sections
    groups = {}
    group_pattern = r"### `svs (\w+)`\n\n(.*?)(?=\n### `svs |\Z)"
    for match in re.finditer(group_pattern, docs, re.DOTALL):
        group_name = match.group(1)
        group_content = match.group(0).strip()
        groups[group_name] = group_content

    return root_docs, groups


def create_root_file(
    template_content: str, root_info: str, groups: dict[str, str]
) -> str:
    """Creates root CLI documentation file with refs to subcommand files."""
    # Build the list of subcommands
    subcommands = "\n".join(
        f"* [`{group}`](./{group}.md)" for group in sorted(groups.keys())
    )

    root_content = f"""{template_content}

{root_info}

## Subcommand Groups

{subcommands}

For detailed documentation on each subcommand, see the files in this directory.
"""
    return root_content


def create_group_file(group_name: str, group_docs: str) -> str:
    """Creates a markdown file for a specific command group."""
    # Upgrade headings since this is now a top-level file
    upgraded_docs = upgrade_headings(group_docs)

    header = f"""# `svs {group_name}`

This page documents all subcommands for the `svs {group_name}` command group.

*This file is auto-generated by the typer docs utility (`docs/compile-cli.py`).*

---

"""
    return header + upgraded_docs


if __name__ == "__main__":
    # Ensure output directory exists
    Path(OUTPUT_DIRECTORY).mkdir(parents=True, exist_ok=True)

    # Generate the full documentation
    docs = generate_docs("svs_core/__main__.py")
    docs = downgrade_headings(docs)

    # Split into groups
    root_docs, groups = split_into_groups(docs)
    root_info = extract_root_command_info(docs)

    # Read template
    with open(TEMPLATE_FILE, "r") as template_file:
        template_content = template_file.read()

    # Create root CLI file
    root_file_content = create_root_file(template_content, root_info, groups)
    with open(OUTPUT_FILE, "w") as f:
        f.write(root_file_content)
    print(f"✓ Generated {OUTPUT_FILE}")

    # Create individual group files
    for group_name, group_docs in sorted(groups.items()):
        group_file = f"{OUTPUT_DIRECTORY}/{group_name}.md"
        group_content = create_group_file(group_name, group_docs)
        with open(group_file, "w") as f:
            f.write(group_content)
        print(f"✓ Generated {group_file}")
