name: Deploy MkDocs site

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocstrings[python] typer

      - name: Install self
        run: |
          pip install -e .

      - name: Compile CLI docs
        run: |
          python docs/compile-cli.py

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
